name: Create Release & Upload To PyPI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+ # add .* to allow dev releases

jobs:
  build:
    name: pythonfinder PyPI Upload
    runs-on: ubuntu-latest
    env:
      CI: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install latest tools for build
        run: |
          python -m pip install build invoke -e .[dev]
      - name: Build wheels
        run: |
          python -m build
      - name: Upload to PyPI via Twine
        # to upload to test pypi, pass --repository-url https://test.pypi.org/legacy/ and use secrets.TEST_PYPI_TOKEN
        run: |
          twine upload --verbose -u '__token__' -p '${{ secrets.PYPI_TOKEN }}' dist/*

      - name: Pre-bump
        run: |
          git config --local user.name 'Github Action'
          git config --local user.email action@github.com
          inv bump-version -t dev
          git commit -am "pre-bump"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
